name: Crash report
description: File a crash dump
title: "[Crash] "
labels: ["bug"]
body:
  - type: textarea
    id: crash-dump
    attributes:
      label: Crash dump
      description: Please copy and paste it. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
